### PR TITLE
Added include/container_view/array_view.hpp

### PR DESCRIPTION
**Pull request by MC-DeltaT**
Defines array_view class template.

### CODE REVIEW

**Comment by MC-DeltaT** [comment]
I'd like this one also tested just a bit by someone else before merging. Probably mistakes in there I overlooked.

**Comment by MC-DeltaT** [comment]
1) I like to write out what's defaulted anyway just so it's obvious that they are still there. Also for the documentation.
2) Yes there should definitely be a constructor from iterators, I'll do that now.
3) It's because we want to separate the `const`ness of the `array_view` object itself and the data that it views. `const` in this case refers to modifying the view, *not* the data. Check [here](http://en.cppreference.com/w/cpp/iterator/reverse_iterator/operator*) in the standard library. If you want `array_view` to view a `const` array then you use `array_view<T const>`.
4) [The standard library uses `noexcept` to mark things that cannot fail in *any* way, not just exceptions](https://stackoverflow.com/q/20517259/7064452). We're not setting a standard here, so we don't need to be as reserved in our use of `noexcept`. I suppose you could argue this one either way, but it cannot throw a C++ exception so I marked it as such. I don't think it's that likely that an out-of-bounds index is passed, especially considering the other, more modern, access methods (e.g. ranged `for`).
5) I considered an equality comparison, BUT, do we make it compare the viewed data or compare the object itself? (I personally am surprised to see this stuff in the [standard library containers](http://en.cppreference.com/w/cpp/container/vector/operator_cmp), having these operators feel a bit ambiguous to me.)

**Comment by MC-DeltaT** [comment]
Actually I'm not so sure about the iterator ctor bit. It would only work with ContiguousIterators obviously. What about passing reverse iterators? And then you've gotta do some jank `&*it` to extract the pointer... I'm not so sure about that.  
Note that `std::string_view` has no such constructor.

**Comment by MC-DeltaT** [comment]
Not going to do the iterator constructor. If you tried to pass even this seemingly-benevolent range: [`c.begin()`, `c.end()`), then the only way to get a pointer would be through `&*(c.end())` which is blatant undefined behaviour.

**Comment by JakobWyatt** [comment]
1. Thanks for the clarification.
3. That's fair enough, just wasn't sure which direction we wanted to go with this.
4. I think we shouldn't set operator[] as noexcept. If there is an apparent performance penalty observed during testing later, then I suppose we could change it to noexcept. But I think that the added debugging ease in some use cases is well worth the speculative performance decreases.
5. Yeah, that's a tough one. I suppose we could leave it out now, and a intuitive use of operator== could emerge after greater use of the library.

**Comment by JakobWyatt** [comment]
For some reason github didnt format my comment properly and changed all my numbers, so:
my no.1 refers to your no.1 
my no.2 refers to your no.3 
my no.3 refers to your no.4 
my no.4 refers to your no.5 

writing up no.2 now

**Comment by JakobWyatt** [comment]
no.2 : Although there isnt a contiguous_iterator_tag yet (fuck you c++17), I still believe that we should include this constructor. As long as we state that behaviour is undefined if the user doesn't pass a ContiguousIterator, then we should be good.
Regarding reverse iterators, they don't satisfy "*(a + n) is equivalent to *(std::addressof(*a) + n)", and therefore do not satisfy ContiguousIterator. So there's no need to worry about them.
To extract the pointer for the start of the array_view, we can simply use std::addressof(*it), which works even if the iterator class defines their own operator&.
To extract the size of the array_view, given [begin, end) we can simply do end - begin + 1, which works because a requirement for ContiguousIterator is to also satisfy RandomAccessIterator.
Regarding your example with c.end(), dereferencing c.end() is not needed, as we can determine the size using the method above and the start iterator using the method above that. Thus, no UB is present.

**Comment by MC-DeltaT** [comment]
The problem is that inside `array_view` a raw pointer is used to point to the viewed data. So in the case of (`c.end()`, `c.end()`], the way you'd get a pointer is via `&*(c.end())` which is very much undefined behaviour. Although realistically you can just check if the range size is zero and then assign `nullptr` internally...  

Iterator tags are deprecated btw.

**Comment by JakobWyatt** [comment]
Also, just in passing, if we want to write out what functions are defaulted shouldn't we also include move ctor and move assignment with that?

**Comment by JakobWyatt** [comment]
In that case we can just check if the range size is zero i guess.

**Comment by MC-DeltaT** [comment]
Oh yeah I skipped the move operators because there's need to have them. Moving scalar types like pointers and integers is pointless. See that `std::string_view` does the same.  

And I'll do the iterator constructor now then.

**Comment by JakobWyatt** [comment]
so for our ctor we have something like:

#include <memory>

constexpr array_view(const_iterator begin, const_iterator end) {
    _size = end - begin;
    if (size == 0) {
        _pointer = nullptr;
    } else {
        _pointer = std::addressof(*begin);
    }
}

**Comment by JakobWyatt** [comment]
whoops i keep forgetting that styling with markdown is supported, and that all my beautiful indentation goes away immediately.

**Comment by MC-DeltaT** [comment]
Except templated to allow other iterator types.

**Comment by MC-DeltaT** [comment]
Check your `noexcept specifier`: it's exactly the same when debugging with or without `noexcept`, so I'm gonna keep it noexcept to show it doesn't throw exceptions.

noexcept true
noexcept false

**Comment by JakobWyatt** [comment]
Whoops I added a commit modifying the noexcept thing before I saw your comment.

**Comment by JakobWyatt** [comment]
Thats only on that compiler though. On some compilers, an unexpected throw from a noexcept function will immediately call std::terminate instead of unwinding the stack.

**Comment by JakobWyatt** [comment]
I'll leave it up to you to implement the iterator ctor how you want though.

**Pull request merged**
